image: node:18

stages:
  - test
  - build
  - deploy

variables:
  RAILWAY_TOKEN: $RAILWAY_TOKEN  # Set this in GitLab CI/CD variables
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA

testBackend:
  stage: test
  variables:
    NODE_ENV: test
  script:
    - cd backend
    - npm install
    - npm test
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
      changes: 
        - backend/**/*


deployBackend:
  stage: deploy
  variables:
    NODE_ENV: development
  script:
    - cd backend/
    - npm install
    - ./node_modules/.bin/railway up --service emse_notesapp_backend --detach
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
      changes: 
        - backend/**/*



